- name: GitHub Webhook Rulebook
  hosts: localhost
  sources:
    - ansible.eda.webhook:
        token: 11bee3da85afee5b50f7a3a20c41fbfb2b2c4fad
  rules:
    - name: React to GitHub Push
      condition: event.payload.action == "opened"
      action:
        run_job_template:
          name: vm  # your AAP job template name
          organization: Default
          extra_vars:
            event: "{{ event }}"
